/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coiltracker;

import java.awt.event.KeyEvent;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mageg
 */
public class CoilTrackerJFrame extends javax.swing.JFrame {

    CoilChanged coilChanged;
    ArrayList<CoilChanged> history = new ArrayList<>();

    ArrayList<CoilChanged> tmp = new ArrayList<>();

    File file = new File("CoilTracker.ct");

    /**
     * Creates new form CoilTrackerJFrame
     */
    public CoilTrackerJFrame() {
        initComponents();

        coilChanged = new CoilChanged();
        this.setTitle("Coil Tracker");

        this.jComboBoxVape.addItem(Mods.Pockex1);
        this.jComboBoxVape.addItem(Mods.Pockex2);
        
        Load();
        Comparison();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxVape = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDateChanged = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelMod1Label = new javax.swing.JLabel();
        jLabelMod2Label = new javax.swing.JLabel();
        jTextFieldMod1SinceLast = new javax.swing.JTextField();
        jTextFieldMod2SinceLast = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxVape.setToolTipText("");

        jLabel1.setText("Which Mod?");

        jLabel2.setText("Date Changed");

        jButtonSave.setText("Save");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(14);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jLabel3.setText("Time since last change");

        jLabelMod1Label.setText("Pockex1");

        jLabelMod2Label.setText("Pockex2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jComboBoxVape, 0, 168, Short.MAX_VALUE)
                        .addComponent(jTextFieldDateChanged))
                    .addComponent(jButtonRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMod1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMod1SinceLast))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMod2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMod2SinceLast)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDateChanged, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemove)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMod1Label)
                                    .addComponent(jTextFieldMod1SinceLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMod2Label)
                                    .addComponent(jTextFieldMod2SinceLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (!"".equals(this.jTextFieldDateChanged.getText())){
        history.add(new CoilChanged((Mods) this.jComboBoxVape.getSelectedItem(), this.jTextFieldDateChanged.getText()));

        } else {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
        String today = sdf.format(new Date());
        history.add(new CoilChanged((Mods) this.jComboBoxVape.getSelectedItem(), today.toString()));    
        }
                Save();

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        // TODO add your handling code here:
        int i = history.size() - 1;
        history.remove(i);
        Save();
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void Load() {
        try {
            FileInputStream fi = new FileInputStream(file);
            ObjectInputStream input = new ObjectInputStream(fi);

            while (true) {
                CoilChanged s = (CoilChanged) input.readObject();
                tmp.add(s);
            }

        } catch (EOFException ex) {
            //Fuck off error
        } catch (IOException | ClassNotFoundException ex) {
        }

        history.addAll(tmp);
        TestSize();
        this.jTextArea1.setText("Mod\tChanged\n");
        this.jTextArea1.append("-----------------------------------\n");

        for (CoilChanged s : history) {
            this.jTextArea1.append(String.format("%s\n", s));
        }

    }

    private void Save() {
        try {
            FileOutputStream fo = new FileOutputStream(file);
            ObjectOutputStream output = new ObjectOutputStream(fo);
            this.jTextArea1.setText("Mod\tChanged\n");
            this.jTextArea1.append("-----------------------------------\n");
            TestSize();
            for (CoilChanged s : history) {
                output.writeObject(s);
//                System.out.println(s);
                this.jTextArea1.append(String.format("%s\n", s));
            }
            output.close();
            fo.close();
        } catch (IOException ex) {
        }

        Comparison();

        this.jTextFieldDateChanged.setText("");
        this.jComboBoxVape.setSelectedItem(Mods.Pockex1);
    }

    /**
     * Tests the size of the ArrayList and removes oldest entries
     */
    private void TestSize() {
        while (history.size() > 10) {
            int i = 0;
            history.remove(i);
            i++;
        }
    }

    /**
     * Compares today's date with the last coil change and gives the difference
     * in days
     */
    private void Comparison() {
        try {
            this.jTextFieldMod1SinceLast.setText("");
            this.jTextFieldMod2SinceLast.setText("");
            // Compare PockeX1
            int i = history.size() - 1;
            while (true) {
                String p1 = Mods.Pockex1.toString();
                String dA = history.get(i).getName().toString();
                if (dA.equals(p1)) {
                    try {
                        Date today = new Date();
                        Date last = new SimpleDateFormat("dd/MM/yy").parse(history.get(i).getDateChanged());
                        long diff = (today.getTime() % last.getTime());
                        int days = (int) TimeUnit.MILLISECONDS.toDays(diff);
                        this.jTextFieldMod1SinceLast.setText(String.format("%d days", days));
                        break;
                    } catch (ParseException ex) {
                        Logger.getLogger(CoilTrackerJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    i--;
                }
            }
            // Compare PockeX2
            i = history.size() - 1;
            while (true) {
                String p1 = Mods.Pockex2.toString();
                String dA = history.get(i).getName().toString();
                if (dA.equals(p1)) {
                    try {
                        Date today = new Date();
                        Date last = new SimpleDateFormat("dd/MM/yy").parse(history.get(i).getDateChanged());
                        long diff = (today.getTime() % last.getTime());
                        int days = (int) TimeUnit.MILLISECONDS.toDays(diff);
                        this.jTextFieldMod2SinceLast.setText(String.format("%d days", days));
                        break;
                    } catch (ParseException ex) {
                        Logger.getLogger(CoilTrackerJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    i--;
                }

            }
        } catch (Exception ex) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoilTrackerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoilTrackerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoilTrackerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoilTrackerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoilTrackerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxVape;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMod1Label;
    private javax.swing.JLabel jLabelMod2Label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDateChanged;
    private javax.swing.JTextField jTextFieldMod1SinceLast;
    private javax.swing.JTextField jTextFieldMod2SinceLast;
    // End of variables declaration//GEN-END:variables
}

